### PR TITLE
Adding workflow to create Jira issues for community activities

### PR DESCRIPTION
**Pull request by Piedone**

### CODE REVIEW

**Comment by wAsnk** [comment]
I'm not sure if I understand, how it works. Will this run on every new push in a PR?

**Comment by Piedone** [comment]
No, just once when a PR is opened. And it'll only create a corresponding Jira review issue if the PR doesn't correspond to a Jira issue already, like this one.

**Comment by wAsnk** [comment]
> No, just once when a PR is opened. And it'll only create a corresponding Jira review issue if the PR doesn't correspond to a Jira issue already, like this one.

Alright, so this one should've already created a new jira issue on NEST? It seems like it didn't happen.

**Comment by Piedone** [comment]
It did, and the corresponding notification also appeared in Teams. But I deleted it.

**Comment by wAsnk** [comment]
> It did, and the corresponding notification also appeared in Teams. But I deleted it.

Alright 🔥 😄

**Review by wAsnk — APPROVED** [review]

**Pull request merged**
