### PR TITLE
NEST-392: Fix and improve spell-checking configuration

### LINKED ISSUE #19: Fix and improve spell-checking configuration (NEST-392)
Because we missed to update the configuration here to adapt to breaking changes in https://github.com/Lombiq/GitHub-Actions.

[Jira issue](https://lombiq.atlassian.net/browse/NEST-392)

### PR DESCRIPTION
**Pull request by BenedekFarkas**
[NEST-392](https://lombiq.atlassian.net/browse/NEST-392)
Fixes #19

We’re still finding out about new stuff in check-spelling! So, what started this is this dev commit and its build: https://github.com/Lombiq/DotNest-Core-SDK/actions/runs/3824823331/jobs/6507381422#step:4:123

What is new to me here is that if you have no custom configuration (i.e., extra dictionaries override) at all, then it won’t be just affected by what’s in the default configuration (in the action/workflow), but it also uses files from LGHA (such as advice.md, excludes.txt, patterns.txt) that otherwise cannot be used as an extra dictionary.

What’s weird is that if we just add advice.md to this repo, then the other two, automatically referenced files (excludes.txt and patterns.txt) won’t be used either from LGHA either, so there will be a lot more unrecognized entries: https://github.com/Lombiq/DotNest-Core-SDK/actions/runs/3829181031/jobs/6515590277#step:4:119

If I copy those two files to this repo, then they will be picked up and there won’t be any unrecognized entries in the spell-checking report: https://github.com/Lombiq/DotNest-Core-SDK/actions/runs/3829279944/jobs/6515803669#step:4:133

Which means that the appsettings.*.json$ pattern doesn’t work with appsettings.development.json if it’s referenced automatically from LGHA (when this repo doesn’t have its own spelling stuff), but it works when it’s in this repository’s own excludes.txt. ¯\\_(ツ)_/¯

On a related note, I added the launchsettings.*.json$ pattern to exclude in this repo but given that we have a bunch of other json file patterns, we should just ignore every json file (in LGHA and other projects too) - at least I don’t know of a counterexample to keep. Command.json doesn’t have unrecognized entries, but that doesn’t need spell checking either.

[NEST-392]: https://lombiq.atlassian.net/browse/NEST-392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NEST-392]: https://lombiq.atlassian.net/browse/NEST-392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Piedone** [comment]
Why do we need all of this configuration if we just want to use the default? This shouldn't be necessary, just as it isn't in OSOCE either. It's also largely copied from LGHA.

**Comment by BenedekFarkas** [comment]
That's because LGHA is actually set up to work for OSOCE, which it shouldn't, because it's supposed to be a generic configuration. I explained the rest in my Jira comment, i.e., as soon as you'd need to add just one entry to any configuration file that is specific to this dictionary, then you need to have your own copy of patterns.txt and excludes.txt.

**Comment by Piedone** [comment]
Let's suppose we don't need anything custom here. Shouldn't

```
  spelling:
    name: Spelling
    uses: Lombiq/GitHub-Actions/.github/workflows/spelling.yml@dev
```

just work, as it does in OSOCE? (There we also have `spell-check-this: Lombiq/GitHub-Actions@dev` but that's only setting the default.) I also have this failing [here](https://github.com/Piedone/DotNest-Sites/actions/runs/3826212103/jobs/6509825715#step:4:123).

**Comment by BenedekFarkas** [comment]
Added my comment on Jira I referred to earlier to the description.

The short answer is ideally, yes (but I still wouldn't use OSOCE as a template, because it has a different "connection" with LGHA), except that based on the origin point of this change (https://github.com/Lombiq/DotNest-Core-SDK/actions/runs/3824823331/jobs/6507381422#step:4:123) it looks like that the same pattern (`appsettings\.*\.json$`) doesn't work the same way in the two different situations: no local config, so everything taken from LGHA vs. local config.

I have one more idea I'll try.

**Comment by BenedekFarkas** [comment]
OK, well... In terms of ignoring `appsettings.development.json`:

1. No local configuration + the pattern in LGHA is `appsettings\.*\.json$`: Doesn't work.
2. Local configuration, the pattern is `appsettings\.*\.json$` (same): Works.
3. No local configuration + the pattern in LGHA is `appsettings.*\.json$`: Works.

 ¯\\_(ツ)_/¯ again. We knew that working with regexes brings annoyances!

We can fix the build with just updating LGHA, but still, if this repo needs just one extra entry in a custom spell-checking dictionary file, then other files need to be added too.

**Comment by 0liver** [comment]
If you want to ignore `appsettings.anything.json` you should be using:

`appsettings\.[^.]+\.json$`

If you also want to ignore `appsettings.json`, then your number 3. cuts it best:

`appsettings.*\.json$`

In your 1. and 2. the `*` applies to the escaped `.` character before it - it's **not** a wildcard as in Windows path search patterns 😉

**Comment by BenedekFarkas** [comment]
Yep, thanks! I tried using `appsettings\.*\.json$`, because that was in patterns.txt before I overhauled it, so I wanted to have a baseline to check against.

**Review by Piedone — APPROVED** [review]
Wow, isn't this a lot harder than it should be! :D

**Comment by Piedone** [comment]
Nothing to merge here. I've re-run the build and now it succeeds: https://github.com/Lombiq/DotNest-Core-SDK/actions/runs/3829896801

**Pull request closed without merging**
